"""Agrego relación entre User y EmailAccount

Revision ID: 0bb56e93c8ba
Revises: 2a463edb83b4
Create Date: 2025-04-07 16:24:00.638092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb56e93c8ba'
down_revision = '2a463edb83b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user'], ['user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
