"""Add identification and identification_type to User

Revision ID: 1b52f91b47e5
Revises: de3b81c742d8
Create Date: 2025-04-25 21:29:58.972642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b52f91b47e5'
down_revision = 'de3b81c742d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identification', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('identification_type', sa.Enum('RUT', 'RUN', 'DNI', 'LC', name='identification_type_enum'), nullable=True))
        batch_op.create_unique_constraint(None, ['identification'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('identification_type')
        batch_op.drop_column('identification')

    # ### end Alembic commands ###
