"""Añadir campos reset_code y reset_code_expiration a User

Revision ID: 2a463edb83b4
Revises: 
Create Date: 2025-04-03 17:24:27.426467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a463edb83b4'
down_revision = '000000000001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    user_columns = {column['name'] for column in inspector.get_columns('users')}

    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('user', sa.String(length=150), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'reset_code' not in user_columns:
            batch_op.add_column(sa.Column('reset_code', sa.String(length=6), nullable=True))
        if 'reset_code_expiration' not in user_columns:
            batch_op.add_column(sa.Column('reset_code_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    user_columns = {column['name'] for column in inspector.get_columns('users')}

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'reset_code_expiration' in user_columns:
            batch_op.drop_column('reset_code_expiration')
        if 'reset_code' in user_columns:
            batch_op.drop_column('reset_code')

    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.drop_column('user')

    # ### end Alembic commands ###
