"""Agrego tabla statuses y relación con users

Revision ID: 8a5fd1d00619
Revises: 368be824829e
Create Date: 2025-04-16 18:07:01.003828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5fd1d00619'
down_revision = '368be824829e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('statuses'):
        op.create_table(
            'statuses',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('code', sa.String(length=20), nullable=False),
            sa.Column('label', sa.String(length=100), nullable=False),
            sa.Column('description', sa.String(length=200), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('code'),
        )

    user_columns = {column['name'] for column in inspector.get_columns('users')}

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'status_id' not in user_columns:
            batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'statuses', ['status_id'], ['id'])
        if 'status' in user_columns:
            batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    user_columns = {column['name'] for column in inspector.get_columns('users')}

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'status' not in user_columns:
            batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        if 'status_id' in user_columns:
            batch_op.drop_constraint(None, type_='foreignkey')
            batch_op.drop_column('status_id')

    if inspector.has_table('statuses'):
        op.drop_table('statuses')

    # ### end Alembic commands ###
