"""Agregar campo deleted_at a User

Revision ID: d360538c96be
Revises: 8a5fd1d00619
Create Date: 2025-04-16 19:03:39.528778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd360538c96be'
down_revision = '8a5fd1d00619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    user_columns = {column['name'] for column in inspector.get_columns('users')}

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'deleted_at' not in user_columns:
            batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    user_columns = {column['name'] for column in inspector.get_columns('users')}

    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'deleted_at' in user_columns:
            batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
