"""Add relation to TermsAndConditions for User

Revision ID: de3b81c742d8
Revises: d360538c96be
Create Date: 2025-04-24 19:03:25.562707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3b81c742d8'
down_revision = 'd360538c96be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terms_and_conditions', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.create_unique_constraint(None, ['version'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_and_conditions_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'terms_and_conditions', ['terms_and_conditions_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('terms_and_conditions_id')

    with op.batch_alter_table('terms_and_conditions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
